### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by hyojoonkim** [rsanger/oflops-turbo#1]
Hello, 

My name is Joon Kim, an engineer at Princeton University. I have found out that you are working on an enhanced version of oflops-turbo (through the WAND blog). I am also interested in measuring packet_in, flow_add, flow_mod/sec performance of hardware switches. I know that you are still in the process, but I want to try your current code. 

I tried to compile your code, but I am running into problems with "make”. I have installed libfuild as the code seems to using that library (https://github.com/OpenNetworkingFoundation/libfluid). 

Is there something that I am missing? I might because I have been just deciphering error messages to have all the requirements and commands. Some help would be appreciated! 

Thanks,
Joon

```
hyojoon@hyojoon-MacVM:~/Work/oflops/oflops-turbo-rsanger/oflops-turbo$ make
make  all-recursive
make[1]: Entering directory `/home/hyojoon/Work/oflops/oflops-turbo-rsanger/oflops-turbo'
Making all in .
make[2]: Entering directory `/home/hyojoon/Work/oflops/oflops-turbo-rsanger/oflops-turbo'
g++ -DHAVE_CONFIG_H -I.    -std=c++11 -Wall -I/home/hyojoon/Work/mininet/openflow/include -I./netfpga-packet-generator-c-library/include/ -Wshadow `pkg-config --cflags libconfig` -g -O2 -MT control.o -MD -MP -MF .deps/control.Tpo -c -o control.o control.cpp
control.cpp: In member function ‘bool BasicTestServer::has_backlog()’:
control.cpp:71:24: error: ‘class fluid_base::OFConnection’ has no member named ‘get_fd’
         fds.fd = conn->get_fd();
                        ^
control.cpp: In function ‘int setup_control_channel(oflops_context*)’:
control.cpp:147:35: error: ‘class fluid_base::OFConnection’ has no member named ‘get_fd’
     fd =ser->get_ofconnection(0)->get_fd();
                                   ^
make[2]: *** [control.o] Error 1
make[2]: Leaving directory `/home/hyojoon/Work/oflops/oflops-turbo-rsanger/oflops-turbo'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/hyojoon/Work/oflops/oflops-turbo-rsanger/oflops-turbo'
make: *** [all] Error 2
```

**Comment by rsanger** [comment]
I have made a minor modification to libfluid to expose the file descriptor. This patch is here https://gist.github.com/rsanger/e7540eb6ebdc759297d5 .

You will also need rofl https://github.com/bisdn/rofl-core to compile the packet in/out tests. The other tests have not been updated and are unlikely to work. My focus has been on the software generation and capture not using NetFPGA so this might have some issues. 

If you have any queries feel free to send me an email (my email is in the commits).

**Comment by hyojoonkim** [comment]
Cool. I was able to successfully compile the code. I'll close this issue. Thanks!
